name: Go

on:
  push:
   branches:
     - "**"
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
       version: latest

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - run: go version

    - name: Build
      run: go build -v ./...


   
    - name: Test
      run: go test -v `go list ./...`

    - name: Coverage
      run: go test `go list ./... ` -coverprofile=coverage.txt -covermode=atomic