name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - run: go version

    - name: Build
      run: go build -v ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.29
    - run: golangci-lint runs
    - name: Test
      run: go test -v `go list ./...`

    - name: Coverage
      run: go test `go list ./... ` -coverprofile=coverage.txt -covermode=atomic