on:
  push:
    tags:
      - '**'

name: Create GH Release
jobs:
 create-release:
  name: Create Terraform Release
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Create Release
      run: gh release create ${{ github.ref }} --generate-notes
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
