on:
  push:
    tags:
      - '**'

name: Create GH Release
jobs:
 create-release:
  name: Create Terraform Release
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Get Tag
      run: |
          set -x
          current_tag=$(git describe --tags --abbrev=0) >> $GITHUB_ENV
          ref=$(git log --oneline --no-decorate "v$current_tag") >> $GITHUB_ENV
          echo " ref : $ref"
    - name: Create Release
      run: gh release create $ref --generate-notes
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
