name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (major or minor)'
        required: true
        default: 'minor'
        options: ['super', 'major', 'minor']


jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get current tag
        id: get_tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Determine next tag
        id: next_tag
        run: |
          echo "NEXT_TAG_SUPER=${{ env.TAG }}" | awk -F. '{print $1}') >> $GITHUB_ENV
          echo "NEXT_TAG_MAJOR=${{ env.TAG }}" | awk -F. '{print $2}') >> $GITHUB_ENV
          echo "NEXT_TAG_MINOR=${{ env.TAG }}" | awk -F. '{print $3}') >> $GITHUB_ENV
          if [[ "${{ github.event.inputs.version }}" == "super" ]]; then
            #super=$(echo "${{ env.TAG }}" | awk -F. '{print $1}')
            super=$((${{ env.NEXT_TAG_SUPER }} + 1))
            echo "NEXT_TAG=v$super.${{ env.NEXT_TAG_MAJOR }}.${{ env.NEXT_TAG_MINOR }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.version }}" == "major" ]]; then
            # major=$(echo "${{ env.TAG }}" | awk -F. '{print $2}')
            major=$((${{ env.NEXT_TAG_MAJOR }} + 1))
            echo "NEXT_TAG=v${{ env.NEXT_TAG_SUPER }}.$major.${{ env.NEXT_TAG_MINOR }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.version }}" == "minor" ]]; then
            # minor=$(echo "${{ env.TAG }}" | awk -F. '{print $3}')
            minor=$((${{ env.NEXT_TAG_MINOR }} + 1))
            echo "NEXT_TAG=v${{ env.NEXT_TAG_SUPER }}.${{ env.NEXT_TAG_MAJOR }}.$minor" >> $GITHUB_ENV
          else
            echo "Invalid version input"
            exit 1
          fi
      - name: Create and push new tag
        run: |
          git tag ${{ env.NEXT_TAG }}
          git push origin main --follow-tags
