name: Create GH Release
on:
  push:
    tags:
      - '**'
jobs:
 create-release:
  name: Create Terraform Release
  runs-on: ubuntu-latest
  permissions:
     contents: write
  steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        node-version: '16'  
    - name: Create Release
      run: gh release create ${{ github.ref }} --generate-notes
      env:
       GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
