name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      triggerString:
        description: 'Enter a string to trigger the workflow'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout power-go-client repo
        uses: actions/checkout@v3
        with:
          repository: michaelkad/power-go-client
          path: power-go-client

      - name: Run Script
        run: |
          # Access the input value using ${{ github.event.inputs.triggerString }}
          echo "Trigger String: ${{ github.event.inputs.triggerString }}"
          # Add your script commands here

