name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      triggerString:
        description: 'Enter a string to trigger the workflow'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout power-beta-go-sdk
        uses: actions/checkout@v3
        with:
          path: go/src/github.com/main

      - name: Checkout power-go-client repo
        uses: actions/checkout@v3
        with:
          repository: michaelkad/terraform-provider-ibm
          path: go/src/github.com/terraform-provider-ibm
          ref: ${{ github.event.inputs.triggerString }}
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: |
          go version
          echo "==> Creating GOPATH/ directory..."
          export GOPATH="$HOME/go"
          export PATH=$PATH:$GOPATH/bin
          mkdir -p $GOPATH $GOPATH/src $GOPATH/pkg $GOPATH/bin
      
      - name: Run Script
        run: |
          sudo apt install gox
          echo "Home: $HOME, Path: $PATH"
          echo "gopath: $GOPATH or  bin: $GOPATH/bin"
          echo "Trigger String: ${{ github.event.inputs.triggerString }}"
          cd  $GOPATH
          ls -la
          cd "/home/runner/work/power-beta-go-sdk/power-beta-go-sdk/go/src/github.com/main"
          chmod +x .github/workflows/build.sh
          .github/workflows/build.sh "${{ github.event.inputs.triggerString }}"
          parent_dir="/home/runner/work/power-beta-go-sdk/power-beta-go-sdk/go/src/github.com/terraform-provider-ibm"
          
          zip_files=""
          while IFS= read -r -d $'\0' file; do
           relative_path="${file#$parent_dir/}"
           zip_files+="$(printf "%q" "$relative_path")\n"
          done < <(find "$parent_dir/pkg" -type f -name "*.zip" -print0)
          if [! -n "$zip_files" ]; then exit 1; fi
          echo -e "Zip files:\n$zip_files"
        env:
         GOPATH: /home/runner/go
      - name: Create release 
        uses: softprops/action-gh-release@v1
        with:
          body: "Testing zip files"
          prerelease: true
          tag_name: v0.0.55-2
          files: |
            "$zip_files"
        

