name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      triggerString:
        description: 'Enter a string to trigger the workflow'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout power-beta-go-sdk
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout power-go-client repo
        uses: actions/checkout@v3
        with:
          repository: michaelkad/power-go-client
          path: power-go-client

      - name: Run Script
        run: |
          echo "Trigger String: ${{ github.event.inputs.triggerString }}"
          echo "Directory : ${PWD}"
          cd "${PWD}/main"
          ls -la
          chmod +x .github/workflows/build.sh
          .github/workflows/build.sh "${{ github.event.inputs.triggerString }}"

