name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      triggerString:
        description: 'Enter a string to trigger the workflow'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go version
      
      - name: Checkout power-beta-go-sdk
        uses: actions/checkout@v3
        with:
          path: go/src/github.com/main

      - name: Checkout power-go-client repo
        uses: actions/checkout@v3
        with:
          repository: michaelkad/terraform-provider-ibm
          path: go/src/github.com/terraform-provider-ibm
          ref: ${{ github.event.inputs.triggerString }}

      
      - name: Run Script
        run: |
          export PATH=$PATH:$GOPATH/bin
          echo "Path: $PATH"
          echo "gopath: $GOPATH or  bin: $GOPATH/bin"
          echo "Trigger String: ${{ github.event.inputs.triggerString }}"
          echo "Directory : ${PWD}"
          cd "$GOPATH/src/github.com/main"
          ls -la
          chmod +x .github/workflows/build.sh
          .github/workflows/build.sh "${{ github.event.inputs.triggerString }}"
#         env:
#          GOPATH: /home/runner/work/power-beta-go-sdk/power-beta-go-sdk/go

